version: "3.8"

services:
  clientes-monolitico:
    build: .
    image: clientes-monolitico:latest
    container_name: clientes-monolitico
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    environment:
      DB_HOST: clientes-monolitico-db
      DB_NAME: clientes_monolitico_db
      DB_USER: monolitico
      DB_PASSWORD: monolitico123
      DB_PORT: "3306"

      VIRTUAL_HOST: clientes.docker.sulbaranjc.com
      VIRTUAL_PORT: "8000"
    depends_on:
      - clientes-monolitico-db
    networks:
      - backend
      - nginx-proxy
    restart: always

  clientes-monolitico-db:
    image: mariadb:10.6
    container_name: clientes-monolitico-db
    environment:
      MYSQL_DATABASE: clientes_monolitico_db
      MYSQL_USER: monolitico
      MYSQL_PASSWORD: monolitico123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - clientes_monolitico_db_data:/var/lib/mysql
      - ./docs/init_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend
    restart: always

networks:
  backend:
    name: clientes_monolitico_backend
  nginx-proxy:
    external: true

volumes:
  clientes_monolitico_db_data:
