version: "3.9"

services:
  app:
    build: .
    container_name: clientes-monolitico
    restart: always
    ports:
      - "8001:8000"
    environment:
      DB_HOST: db
      DB_NAME: clientes_db
      DB_USER: clientes
      DB_PASSWORD: clientes123
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mariadb:10.6
    container_name: clientes-db
    restart: always
    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: clientes
      MYSQL_PASSWORD: clientes123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - clientes_db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - backend

volumes:
  clientes_db_data:

networks:
  backend:
    external: true
