services:
  app:
    build: .
    container_name: clientes-monolitico
    restart: always

    environment:
      DB_HOST: clientes-db   # ðŸ‘ˆ ESTE ES EL FIX
      DB_NAME: clientes_db
      DB_USER: clientes
      DB_PASSWORD: clientes123
      DB_PORT: 3306

      VIRTUAL_HOST: clientes.docker.sulbaranjc.com
      VIRTUAL_PORT: "8000"

    expose:
      - "8000"

    depends_on:
      - db

    networks:
      - nginx-proxy
      - internal
