services:
  app:
    image: clientes-app:latest
    container_name: clientes-monolitico
    restart: always

    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"

    expose:
      - "8000"

    environment:
      DB_HOST: db
      DB_NAME: clientes_db
      DB_USER: clientes
      DB_PASSWORD: clientes123
      DB_PORT: "3306"

      VIRTUAL_HOST: clientes.docker.sulbaranjc.com
      VIRTUAL_PORT: "8000"

    depends_on:
      - db

    networks:
      - backend
      - nginx-proxy

  db:
    image: mariadb:10.6
    container_name: clientes-db
    restart: always

    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: clientes
      MYSQL_PASSWORD: clientes123
      MYSQL_ROOT_PASSWORD: root123

    volumes:
      - clientes_db_data:/var/lib/mysql

    networks:
      - backend

networks:
  backend:
  nginx-proxy:
    external: true

volumes:
  clientes_db_data:
