services:
  clientes-monolitico:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clientes-monolitico
    restart: always

    environment:
      DB_HOST: clientes-monolitico-db
      DB_NAME: clientes_db
      DB_USER: clientes
      DB_PASSWORD: clientes123
      DB_PORT: "3306"

      VIRTUAL_HOST: clientes.docker.sulbaranjc.com
      VIRTUAL_PORT: "8000"

    expose:
      - "8000"

    depends_on:
      - clientes-monolitico-db

    networks:
      - backend
      - nginx-proxy

  clientes-monolitico-db:
    image: mariadb:10.6
    container_name: clientes-monolitico-db
    restart: always

    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: clientes
      MYSQL_PASSWORD: clientes123
      MYSQL_ROOT_PASSWORD: root123

    volumes:
      - clientes_monolitico_db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

    networks:
      - backend

networks:
  backend:
    name: clientes_monolitico_backend

  nginx-proxy:
    external: true

volumes:
  clientes_monolitico_db_data:
