services:
  clientes-monolitico:
    build: .
    container_name: clientes-monolitico
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      VIRTUAL_HOST: clientes-monolitico.docker.sulbaranjc.com
      VIRTUAL_PORT: "8000"
    expose:
      - "8000"
    networks:
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true
